CREATE TABLE OPPGAVE (
    JOURNALPOST_ID VARCHAR(32) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ENHET VARCHAR(10) NOT NULL,
    FRIST TIMESTAMP(3) NOT NULL,
    BRUKER_ID VARCHAR(19),
    YTELSE_TYPE VARCHAR(20),
    BESKRIVELSE VARCHAR(200),
    RESERVERT_AV VARCHAR(20),
    VERSJON INTEGER NOT NULL DEFAULT 0,
    OPPRETTET_AV VARCHAR(20) NOT NULL DEFAULT 'VL',
    OPPRETTET_TID TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ENDRET_AV VARCHAR(20),
    ENDRET_TID TIMESTAMP(3),
    CONSTRAINT PK_OPPGAVE PRIMARY KEY (JOURNALPOST_ID)
);

COMMENT ON TABLE OPPGAVE IS 'Inneholder oppgaver som skal løses av saksbehandlere i journalføring.';
COMMENT ON COLUMN OPPGAVE.STATUS IS 'Status av oppgaven. Foreløpig AAPENT, FERDIGSTILT.';
COMMENT ON COLUMN OPPGAVE.JOURNALPOST_ID IS 'ID til journalposten i JOARK';
COMMENT ON COLUMN OPPGAVE.BRUKER_ID IS 'ID til avsenderen av et dokument';
COMMENT ON COLUMN OPPGAVE.YTELSE_TYPE IS 'YtelseType fra kodeverk. FP, SVP, EN';
COMMENT ON COLUMN OPPGAVE.BESKRIVELSE IS 'Oppgave beskrivelse.';
COMMENT ON COLUMN OPPGAVE.ENHET IS 'Tildelt enhet som skal løse oppgaven.';
COMMENT ON COLUMN OPPGAVE.FRIST IS 'Frist dato for å løse oppgaven.';
COMMENT ON COLUMN OPPGAVE.RESERVERT_AV IS 'Lagrer identen til SBH som reserverer oppgaven.';
COMMENT ON COLUMN OPPGAVE.VERSJON IS 'Teknisk versjonering av endringer.';

CREATE INDEX idx_oppgave_status_enhet ON OPPGAVE (STATUS, ENHET);
